// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: state_scem.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WorkflowModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkflowProcessID      string `protobuf:"bytes,1,opt,name=WorkflowProcessID,json=workflow_process_id,proto3" json:"WorkflowProcessID,omitempty"`
	WorkflowVersion        int32  `protobuf:"varint,2,opt,name=WorkflowVersion,json=workflow_version,proto3" json:"WorkflowVersion,omitempty"`
	WorkflowKey            string `protobuf:"bytes,3,opt,name=WorkflowKey,json=workflow_key,proto3" json:"WorkflowKey,omitempty"`
	Step                   int32  `protobuf:"varint,4,opt,name=Step,json=step,proto3" json:"Step,omitempty"`
	Type                   int32  `protobuf:"varint,5,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	Name                   string `protobuf:"bytes,6,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	NextStep1              int32  `protobuf:"varint,7,opt,name=NextStep1,json=next_step_1,proto3" json:"NextStep1,omitempty"`
	NextStep2              int32  `protobuf:"varint,8,opt,name=NextStep2,json=next_step_2,proto3" json:"NextStep2,omitempty"`
	ServiceRetry           int32  `protobuf:"varint,9,opt,name=ServiceRetry,json=service_retry,proto3" json:"ServiceRetry,omitempty"`
	MessageCorrelationName string `protobuf:"bytes,10,opt,name=MessageCorrelationName,json=message_correlation_name,proto3" json:"MessageCorrelationName,omitempty"`
}

func (x *WorkflowModel) Reset() {
	*x = WorkflowModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_scem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowModel) ProtoMessage() {}

func (x *WorkflowModel) ProtoReflect() protoreflect.Message {
	mi := &file_state_scem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowModel.ProtoReflect.Descriptor instead.
func (*WorkflowModel) Descriptor() ([]byte, []int) {
	return file_state_scem_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowModel) GetWorkflowProcessID() string {
	if x != nil {
		return x.WorkflowProcessID
	}
	return ""
}

func (x *WorkflowModel) GetWorkflowVersion() int32 {
	if x != nil {
		return x.WorkflowVersion
	}
	return 0
}

func (x *WorkflowModel) GetWorkflowKey() string {
	if x != nil {
		return x.WorkflowKey
	}
	return ""
}

func (x *WorkflowModel) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *WorkflowModel) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WorkflowModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowModel) GetNextStep1() int32 {
	if x != nil {
		return x.NextStep1
	}
	return 0
}

func (x *WorkflowModel) GetNextStep2() int32 {
	if x != nil {
		return x.NextStep2
	}
	return 0
}

func (x *WorkflowModel) GetServiceRetry() int32 {
	if x != nil {
		return x.ServiceRetry
	}
	return 0
}

func (x *WorkflowModel) GetMessageCorrelationName() string {
	if x != nil {
		return x.MessageCorrelationName
	}
	return ""
}

type DeployWorkflowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkflowModel []*WorkflowModel `protobuf:"bytes,1,rep,name=workflowModel,proto3" json:"workflowModel,omitempty"`
}

func (x *DeployWorkflowRequest) Reset() {
	*x = DeployWorkflowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_scem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWorkflowRequest) ProtoMessage() {}

func (x *DeployWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_scem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWorkflowRequest.ProtoReflect.Descriptor instead.
func (*DeployWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_state_scem_proto_rawDescGZIP(), []int{1}
}

func (x *DeployWorkflowRequest) GetWorkflowModel() []*WorkflowModel {
	if x != nil {
		return x.WorkflowModel
	}
	return nil
}

type DeployWorkflowlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkflowKey string `protobuf:"bytes,1,opt,name=WorkflowKey,json=workflow_key,proto3" json:"WorkflowKey,omitempty"`
	Ok          bool   `protobuf:"varint,2,opt,name=Ok,json=ok,proto3" json:"Ok,omitempty"`
}

func (x *DeployWorkflowlResponse) Reset() {
	*x = DeployWorkflowlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_state_scem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployWorkflowlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWorkflowlResponse) ProtoMessage() {}

func (x *DeployWorkflowlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_scem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWorkflowlResponse.ProtoReflect.Descriptor instead.
func (*DeployWorkflowlResponse) Descriptor() ([]byte, []int) {
	return file_state_scem_proto_rawDescGZIP(), []int{2}
}

func (x *DeployWorkflowlResponse) GetWorkflowKey() string {
	if x != nil {
		return x.WorkflowKey
	}
	return ""
}

func (x *DeployWorkflowlResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_state_scem_proto protoreflect.FileDescriptor

var file_state_scem_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x63, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xe8, 0x02, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x11, 0x57, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x13, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x5f, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x74, 0x65, 0x70, 0x31, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x74, 0x65, 0x70,
	0x5f, 0x31, 0x12, 0x1e, 0x0a, 0x09, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x74, 0x65, 0x70, 0x32, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x74, 0x65, 0x70,
	0x5f, 0x32, 0x12, 0x23, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x74,
	0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x79, 0x12, 0x38, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x50, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0d, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x4c, 0x0a, 0x17, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x57, 0x6f, 0x72,
	0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x6b, 0x65,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x32, 0x5e, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x57,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x57, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_state_scem_proto_rawDescOnce sync.Once
	file_state_scem_proto_rawDescData = file_state_scem_proto_rawDesc
)

func file_state_scem_proto_rawDescGZIP() []byte {
	file_state_scem_proto_rawDescOnce.Do(func() {
		file_state_scem_proto_rawDescData = protoimpl.X.CompressGZIP(file_state_scem_proto_rawDescData)
	})
	return file_state_scem_proto_rawDescData
}

var file_state_scem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_state_scem_proto_goTypes = []interface{}{
	(*WorkflowModel)(nil),           // 0: pb.WorkflowModel
	(*DeployWorkflowRequest)(nil),   // 1: pb.DeployWorkflowRequest
	(*DeployWorkflowlResponse)(nil), // 2: pb.DeployWorkflowlResponse
}
var file_state_scem_proto_depIdxs = []int32{
	0, // 0: pb.DeployWorkflowRequest.workflowModel:type_name -> pb.WorkflowModel
	1, // 1: pb.StateScemService.DeployWorkflow:input_type -> pb.DeployWorkflowRequest
	2, // 2: pb.StateScemService.DeployWorkflow:output_type -> pb.DeployWorkflowlResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_state_scem_proto_init() }
func file_state_scem_proto_init() {
	if File_state_scem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_state_scem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_scem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployWorkflowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_state_scem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployWorkflowlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_state_scem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_state_scem_proto_goTypes,
		DependencyIndexes: file_state_scem_proto_depIdxs,
		MessageInfos:      file_state_scem_proto_msgTypes,
	}.Build()
	File_state_scem_proto = out.File
	file_state_scem_proto_rawDesc = nil
	file_state_scem_proto_goTypes = nil
	file_state_scem_proto_depIdxs = nil
}
